import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/About.module.css";
import HeaderSmall from "@/components/HeaderSmall";
import GetQuoteForm from "@/components/GetQuoteForm";
import Pkg from "@/components/Pkg";
import Footer from "@/components/Footer";
import { useState } from "react";
import { useEffect } from "react";
import Spinner from '@/public/Spinner.gif'

const inter = Inter({ subsets: ["latin"] });


export default function About() {

  return (
    <>
      <Head>
        <title>About Us | Umrah Insights</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderSmall title="About Us"/>
      <main id="main" className="container my-5">
        <h1 id={styles.mainHeading} className="text-center">About <span className="span"></span></h1>
        <div>
            
        </div>
      </main>
      <Footer/>
    </>
  );
}